scriptencoding utf-8
set encoding=utf-8
set nocompatible            " disable vi compatibility
" filetype off                " required

" using vim-plug
call plug#begin('~\.vim\plugged')

" Sensible defaults for vim
Plug 'tpope/vim-sensible'

" Python PEP 8 checking - requires flake8
" pip install flake8
Plug 'nvie/vim-flake8'

" Solarized Colorscheme
Plug 'altercation/vim-colors-solarized'

" Syntax highlighting
Plug 'Markdown'

" Git wrapper for vim
Plug 'tpope/vim-fugitive'

" Vim support for Julia
Plug 'JuliaLang/julia-vim'

" insert or delete brackets, parens, quotes
Plug 'jiangmiao/auto-pairs'

" add all plugins before this line
call plug#end()

filetype plugin indent on
syntax enable

" Solarized colorscheme for Vim
" solarized everywhere
if has('gui_running')
    set background=dark
    colorscheme solarized
else
    set background=light
    set t_Co=256
    let g:solarized_termcolors=256
    colorscheme solarized
endif

" Vim has spellcheck
" set spell
" ]s [s
" zg zw z= 1z=
" .vim/spell/en.utf-8.add

" Store the swp and backup files in a sparate directory
" Dropbox is syncing hidden files also :-)
" set dir=~/.vim/swap,/tmp,.
" set bdir=~/.vim/backup,/tmp,.
set nobackup
set nowritebackup

" List chars
set list
set listchars=""
" set listchars=tab:»·
set listchars=tab:▸\ 
set listchars+=trail:·
set listchars+=extends:>
set listchars+=precedes:<
set listchars+=nbsp:·
set listchars+=eol:¬


set backspace=indent,eol,start

" Text , tab and Indentation Related
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab

set linebreak
set textwidth=500
set colorcolumn=80

" set autoindent
" set smartindent
set wrap            "Wrap Lines

set number          " line numbers on
set showmatch       " show matching brackets

"set guifont=Monaco\ 10 "If this does not work google
if has('gui_running')
    " set guifont=Inconsolata\ 14
    set guifont=Consolas:h12:cDEFAULT:
endif

set hlsearch        " highlight search
set ignorecase      " do case insensitive matching
set smartcase       " be sensitive when there's a capital letter
set incsearch

" Abbreviations
abbreviate #i #include
abbreviate #d #define

" Remove the toolbar
" this makes it look clean in windows as gvim on windows has bad toolbar
" icons
if has('gui_running')
    set guioptions-=T   " remove toolbar icons
    set guioptions-=m   " remove menu bar to give a terminal like feel
    set guioptions-=r   " remove right-hand scroll bar
    set guioptions-=L   " remove left-hand scroll bar
endif
" set guioptions-=T   " remove toolbar icons
" set guioptions-=m   " remove menu bar to give a terminal like feel

" use <C-b> to paste from system clipboard
" <C-v> is already used in Vim to trigger Visual Block mode
map <C-b> "+p

" use <C-c> to copy to system clipboard
" the text to copy should be selected using visual mode
map <C-c> "+y

" disable error bell
set noerrorbells visualbell t_vb=
if has('autocmd')
    autocmd GUIEnter * set visualbell t_vb=
endif
