scriptencoding utf-8
set encoding=utf-8
set nocompatible            " disable vi compatibility
" filetype off                " required

" using vim-plug
call plug#begin('~/.vim/plugged')

" Sensible defaults for vim
Plug 'tpope/vim-sensible'

" Python PEP 8 checking - requires flake8
" pip install flake8
Plug 'nvie/vim-flake8'

" Solarized Colorscheme
Plug 'altercation/vim-colors-solarized'

" Syntax highlighting
Plug 'Markdown'

" Git wrapper for vim
Plug 'tpope/vim-fugitive'

" Vim support for Julia
Plug 'JuliaLang/julia-vim'

" insert or delete brackets, parens, quotes
Plug 'jiangmiao/auto-pairs'

" add all plugins before this line
call plug#end()

filetype plugin indent on
syntax enable

set background=dark
" set t_Co=256
colorscheme industry

" Vim has spellcheck
" set spell
" ]s [s
" zg zw z= 1z=
" .vim/spell/en.utf-8.add

" Store the swp and backup files in a sparate directory
" Dropbox is syncing hidden files also :-)
" set dir=~/.vim/swap,/tmp,.
" set bdir=~/.vim/backup,/tmp,.
set nobackup
set nowritebackup

" List chars
set list
set listchars=""
" set listchars=tab:»·
set listchars=tab:▸\ 
set listchars+=trail:·
set listchars+=extends:>
set listchars+=precedes:<
set listchars+=nbsp:·
set listchars+=eol:¬


set backspace=indent,eol,start

" Text , tab and Indentation Related
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab

set linebreak
set textwidth=500
set colorcolumn=80

" set autoindent
" set smartindent
set wrap            "Wrap Lines

set number          " line numbers on
set showmatch       " show matching brackets


set hlsearch        " highlight search
set ignorecase      " do case insensitive matching
set smartcase       " be sensitive when there's a capital letter
set incsearch

" Abbreviations
abbreviate #i #include
abbreviate #d #define

" use <C-b> to paste from system clipboard
" <C-v> is already used in Vim to trigger Visual Block mode
map <C-b> "+p

" use <C-c> to copy to system clipboard
" the text to copy should be selected using visual mode
map <C-c> "+y

" disable error bell
set noerrorbells visualbell t_vb=
if has('autocmd')
    autocmd GUIEnter * set visualbell t_vb=
endif
